name: ddgcrn
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0=mkl
  - certifi=2021.5.30=py36haa95532_0
  - cudatoolkit=10.1.243=h74a9793_0
  - dataclasses=0.8=pyh4f3eec9_6
  - freetype=2.13.3=h0620614_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jpeg=9b=hb83a4c4_2
  - lerc=4.0.0=h5da7b33_0
  - libdeflate=1.17=h2bbff1b_1
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.0=h8a3f274_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36h196d8e1_0
  - mkl_fft=1.3.0=py36h46781fe_0
  - mkl_random=1.1.1=py36h47e9c7a_0
  - ninja=1.13.1=haa95532_0
  - ninja-base=1.13.1=h512dff2_0
  - numpy-base=1.19.2=py36ha3acd2a_0
  - olefile=0.46=pyhd3eb1b0_0
  - pandas=1.1.5=py36hd77b12b_0
  - python=3.6.5=h0c2934d_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytorch=1.8.1=py3.6_cuda10.1_cudnn7_0
  - pytz=2021.3=pyhd3eb1b0_0
  - setuptools=58.0.4=py36haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - tk=8.6.15=hf199647_0
  - torchaudio=0.8.1=py36
  - torchvision=0.9.1=py36_cu101
  - typing_extensions=4.1.1=pyh06a4308_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - configparser==5.2.0
      - numpy==1.16.3
      - pillow==8.4.0
      - pip==21.3.1
prefix: C:\Users\C Baker\.conda\envs\ddgcrn
